from __future__ import annotations

from enum import StrEnum


class OrderStatus(StrEnum):
    PAID = "PAID"
    PROCESSING = "PROCESSING"
    SHIPPED = "SHIPPED"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"


class ActionType(StrEnum):
    CANCEL_ORDER = "CANCEL_ORDER"
    RETURN_ITEM = "RETURN_ITEM"
    EXCHANGE_ITEM = "EXCHANGE_ITEM"


class ApprovalStatus(StrEnum):
    PREPARED = "PREPARED"
    PRESENTED = "PRESENTED"
    CONFIRMED = "CONFIRMED"
    EXECUTING = "EXECUTING"
    EXECUTED = "EXECUTED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class ConfirmationSource(StrEnum):
    BUTTON = "BUTTON"
    EXACT_TEXT = "EXACT_TEXT"


class ItemCondition(StrEnum):
    NEW_UNWORN = "NEW_UNWORN"
    OPENED_UNUSED = "OPENED_UNUSED"
    USED = "USED"
    DAMAGED = "DAMAGED"


class EvidenceKind(StrEnum):
    INVOICE = "INVOICE"
    LOGISTICS_LABEL = "LOGISTICS_LABEL"
    DEFECT_PHOTO = "DEFECT_PHOTO"
    WRONG_ITEM_PHOTO = "WRONG_ITEM_PHOTO"


class IssueType(StrEnum):
    CHANGED_MIND = "CHANGED_MIND"
    SIZE_MISMATCH = "SIZE_MISMATCH"
    WRONG_ITEM = "WRONG_ITEM"
    DEFECTIVE = "DEFECTIVE"
    DAMAGED_IN_TRANSIT = "DAMAGED_IN_TRANSIT"


class EligibilityReason(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    ORDER_NOT_OWNED = "ORDER_NOT_OWNED"
    ITEM_NOT_FOUND = "ITEM_NOT_FOUND"
    ORDER_ALREADY_CANCELLED = "ORDER_ALREADY_CANCELLED"
    ORDER_ALREADY_SHIPPED = "ORDER_ALREADY_SHIPPED"
    ORDER_NOT_DELIVERED = "ORDER_NOT_DELIVERED"
    RETURN_WINDOW_EXPIRED = "RETURN_WINDOW_EXPIRED"
    FINAL_SALE = "FINAL_SALE"
    ITEM_CONDITION_NOT_ALLOWED = "ITEM_CONDITION_NOT_ALLOWED"
    TARGET_SIZE_REQUIRED = "TARGET_SIZE_REQUIRED"
    TARGET_SIZE_UNCHANGED = "TARGET_SIZE_UNCHANGED"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    ACTIVE_REQUEST_EXISTS = "ACTIVE_REQUEST_EXISTS"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"
    INVALID_ACTION = "INVALID_ACTION"


class RequestStatus(StrEnum):
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ITEM_RECEIVED = "ITEM_RECEIVED"
    COMPLETED = "COMPLETED"


class TicketStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"


class TicketPriority(StrEnum):
    NORMAL = "NORMAL"
    HIGH = "HIGH"
